vich_uploader:
    db_driver: orm

    mappings:
       cover_image:
            uri_prefix: upload/images/cover
            upload_destination: '%kernel.project_dir%/public/upload/images/cover'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


