controllers:
    resource: ../../src/Controller/
    type: annotation
    # this is added to the beginning of all imported route URLs
    prefix: '/{_locale}'
    # this is added to the beginning of all imported route names
    # these requirements are added to all imported routes
    requirements:
        locale: 'en|es|fr'
    # An imported route with an empty URL will become "/blog/"
    # Uncomment this option to make that URL "/blog" instead
    # trailing_slash_on_root: false
